In [5]:
import pandas as pd

In [41]:
df = pd.read_excel('energy-matrix.xlsx')

In [42]:
df.head()

,Continent,production_consumption,type_of_energy,1980,1981,1982,1983,1984,1985,1986,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Europe,Production,Coal,20.381340,20.297834,21.050901,21.053260,19.829260,21.401627,21.805690,...,8.016302,7.445686,7.035136,6.896194,6.519854,6.432283,6.223739,5.587662,4.740765,5.078592
1,Europe,Production,Natural gas (quad Btu),8.776540,8.640931,8.253435,8.504295,8.593558,8.782232,8.715006,...,10.172471,9.893549,9.229487,9.104128,9.045085,9.164586,8.703050,8.108205,7.503836,7.204944
2,Europe,Production,Petroleum and other liquids (quad Btu),6.277921,6.639482,7.409406,8.346887,8.927659,9.230961,9.535800,...,7.155796,6.755609,6.830088,7.129615,7.222234,7.102020,7.043460,6.800130,7.208758,6.899340
3,Europe,Production,"Nuclear, renewables, and other (quad Btu)",7.472297,8.249006,8.555073,9.362117,10.530915,11.493725,11.859150,...,19.371844,20.286282,20.613760,20.819139,20.815149,20.827342,21.591485,21.730309,21.138669,21.383927
4,Europe,Consumption,Coal,22.720847,22.652893,23.006503,23.193848,23.167302,24.503249,24.669310,...,13.964657,13.560428,12.942157,12.734685,11.999272,12.064695,11.520972,9.716156,8.261265,8.794819

In [43]:
df = df[['Continent', 'production_consumption', 'type_of_energy', 2015, 2016, 2017, 2018, 2019, 2020]]

df.head()

,Continent,production_consumption,type_of_energy,2015,2016,2017,2018,2019,2020
0,Europe,Production,Coal,6.896194,6.519854,6.432283,6.223739,5.587662,4.740765
1,Europe,Production,Natural gas (quad Btu),9.104128,9.045085,9.164586,8.703050,8.108205,7.503836
2,Europe,Production,Petroleum and other liquids (quad Btu),7.129615,7.222234,7.102020,7.043460,6.800130,7.208758
3,Europe,Production,"Nuclear, renewables, and other (quad Btu)",20.819139,20.815149,20.827342,21.591485,21.730309,21.138669
4,Europe,Consumption,Coal,12.734685,11.999272,12.064695,11.520972,9.716156,8.261265

In [44]:
df2 = pd.melt(df, id_vars=["Continent", "production_consumption", "type_of_energy"],
             var_name="year", value_name="value")

In [45]:
df2.head()

,Continent,production_consumption,type_of_energy,year,value
0,Europe,Production,Coal,2015,6.896194
1,Europe,Production,Natural gas (quad Btu),2015,9.104128
2,Europe,Production,Petroleum and other liquids (quad Btu),2015,7.129615
3,Europe,Production,"Nuclear, renewables, and other (quad Btu)",2015,20.819139
4,Europe,Consumption,Coal,2015,12.734685

In [47]:
df2.to_excel('energy-matrix2.xlsx')